Ewm-Statistic
AdalizEentropy/java-explore-with-me pull request #1
Opened 2023-01-29 16:31 UTC by AdalizEentropy

Этап 1. Сервис статистики

2023-01-31 00:55 UTC, NikolaiDem requested changes

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-client/src/main/java/ru/practicum/stat/client/StatClient.java
> +public interface StatClient {
implements StatClient ?

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-client/src/main/java/ru/practicum/stat/client/StatClientImpl.java
> +    public Object getStat(ViewStatsDtoReq viewStatsDtoReq) {
Почему Object, а не ViewStatsDtoResp?

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-dto/src/main/java/ru/practicum/stat/view/ViewStatsDtoReq.java
> +    private String[] uris;
List был бы удобнее)

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-dto/src/main/java/ru/practicum/stat/view/ViewStatsParam.java
> +    private String[] uris;
List?

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-server/src/main/java/ru/practicum/stat/dao/StatRepository.java
> +public interface StatRepository extends JpaRepository<Statistic, Long> {
Статистика будет собираться и не по всем uri, а по некоторому списку, например. Тогда в запросы можно добавить условие по uri.

2023-01-31 00:55 UTC, NikolaiDem commented on statistic/stat-server/src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS statistics (
Еще лучше сделать таблицу с приложениями, где будет его id и название.
Таким образом при изменении, например, названия приложения не придется обновлять всю таблицу statistics .

2023-01-31 17:18 UTC, AdalizEentropy commented on statistic/stat-client/src/main/java/ru/practicum/stat/client/StatClient.java
> +public interface StatClient {
Упс )))

2023-01-31 17:35 UTC, AdalizEentropy commented on statistic/stat-server/src/main/java/ru/practicum/stat/dao/StatRepository.java
> +public interface StatRepository extends JpaRepository<Statistic, Long> {
Я сделала это через маппинг в коде. Ну оке, переделала на запрос в БД со списком uri

2023-02-01 01:00 UTC, NikolaiDem approved these changes

2023-02-01 15:47 UTC, closed without merging